kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ikshvaku
subjects:
- kind: ServiceAccount
  name: ikshvaku
roleRef:
  kind: Role
  name: ikshvaku
  apiGroup: rbac.authorization.k8s.io
